import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'react-hot-toast'
import SessionProvider from './Components/SessionProvider.jsx';
import { getServerSession } from 'next-auth';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <Toaster
            toastOptions={{
              style: {
                background: 'rgb(51,65,85)',
                color: 'white'
              }
            }}
          />
          <SessionProvider session={session}>
            {children}
          </SessionProvider>
        </body>

      </html>
    </>
  )
}
